# Generated by Django 4.1 on 2022-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_contactpersonphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='invitee_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
