# Generated by Django 4.1 on 2022-08-13 19:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_invitee_invitee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitation_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_whatsapp_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitation_email_content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
