# Generated by Django 4.1 on 2022-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_invitation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='invitee_rsvp_reject',
            field=models.BooleanField(default=False),
        ),
    ]
