# Generated by Django 4.1 on 2022-08-12 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_done', models.BooleanField(default=False)),
                ('rsvp_reject', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('guest_count', models.DecimalField(decimal_places=0, default=1, max_digits=1)),
                ('name_for_invitation_without_registering', models.CharField(blank=True, max_length=100, null=True)),
                ('email_for_invitation_without_registering', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_for_invitation_without_registering', models.CharField(blank=True, max_length=11, null=True)),
                ('eventcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('invitation_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
